### ISSUE TITLE
Big gay think a shitty obfuscator i made about 1 years+ ago is "skidded"

### ISSUE THREAD

**Issue by ZeptarTeam** [call-042PE/VaporObfuscator#1]
gay

**Comment by call-042PE** [comment]
My repository has been created like 1years+, he repository has been created 1 month ago are u braindead ?
You know why we have the same features ? It's because this is the easiest features to implement in an obfuscator any newbie with dnlib can do the same thing, and remember if i was "skidding" things i will be skidding better obfuscator like confuserex or koivm.
![issou](https://image.noelshack.com/fichiers/2021/21/5/1622189246-issou.png)

**Comment by ZeptarTeam** [comment]
# im gay 😂

**Comment by call-042PE** [comment]
![braindead](https://image.noelshack.com/fichiers/2021/21/5/1622196913-braindead.png)
